FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Pass NEXT_PUBLIC_API_URL dynamic later via ENV if possible, or build it dynamically
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
